name: hiv_growth_rate

channels:
  - conda-forge

dependencies:
  - r-base=4.1.3
  - r-dplyr=1.0.9
  - r-tidyr=1.2.0
  - r-stringr=1.4.0
  - r-readr=2.1.2
  - r-ggplot2=3.3.6
  - r-cowplot=1.1.1
  - r-colorspace=2.0_3
  - r-ggtext=0.1.1
  - r-gridtext=0.1.4
