name: hiv_growth_rate

channels:
  - conda-forge

dependencies:
  - r-base=3.5.1
  - r-dplyr=0.8.3
  - r-tidyr=0.8.3
  - r-stringr=1.4.0
  - r-readr=1.3.1
  - r-ggplot2=3.3.0
  - r-cowplot=1.0.0
  - r-colorspace=1.4_1
  - r-tidytext=0.2.2
  - r-ggtext=0.1.0
  - r-gridtext=0.1.1
